apiVersion: v1
kind: Template
metadata:
  name: build-analysers
  labels:
    template: build-analysers
    app: thoth
    component: build-analyser-controller
  annotations:
    description: >
      This is Thoth Core - Build Analyser CRD Controller
    openshift.io/display-name: Thoth Core
    version: 0.2.0
    tags: poc,thoth,ai-stacks,build-analysers
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        service: build-analyser-controller
        app: thoth
        component: build-analyser-controller
      name: build-analyser
    spec:
      replicas: 1
      selector:
        service: build-analyser-controller
      template:
        metadata:
          labels:
            service: build-analyser-controller
            app: thoth
            component: build-analyser-controller
        spec:
          containers:
            - name: build-analyser-controller
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "500m"
                limits:
                  memory: "256Mi"
                  cpu: "1000m"
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - build-analyser
            from:
              kind: ImageStreamTag
              name: 'build-analyser:latest'
