kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bla
rules:
  - apiGroups:
      - thoth-station.ninja
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-bla
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: bla
  apiGroup: rbac.authorization.k8s.io
